sudo: required

services:
  - docker

before_install:
  - docker build -t mohamedsaihii/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mohamedsaihii/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-3-654654318632"
  bucket_path: "frontend"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: "$AWS_SECRET_KEY"
